services:
  postgres:
    image: postgres:15-alpine
    container_name: barbershop_core_db
    restart: always
    environment:
      POSTGRES_USER: barberUser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: barbershop_core_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_core_data:/var/lib/postgresql/data

volumes:
  postgres_core_data:
